### ISSUE TITLE
Merge 'Point of Contact' and 'Responsible Party' sections in the IYS CKAN interface

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/ckan#12]
**Is your feature request related to a problem? Please describe.**
It's unclear to users what roles they select end up in the Point of Contact and Responsible Party sections of CKAN. For eg. "What does it mean to be the Point of Contact? Isn't everyone listed a potential point of contact depending on the nature of the inquiry (data related vs metadata related for example)". "What does it mean to be the Responsible Party?" These are questions asked by users of the IYS/CIOOS Metadata intake form.

**Describe the solution you'd like**
Merge the Point of Contact and Responsible Party sections and label the new combined sections "Points of Contact'"

**Describe alternatives you've considered**
The alternative would be to clarify in the metadata intake form what roles end up in the Points of Contact vs Responsible Party section in the CKAN record. I think this might be too much information that doesn't really have any meaning for the user. 

**Additional context**

![image](https://user-images.githubusercontent.com/26495640/125525731-c87ba815-c0f4-4783-8360-00180df58293.png)

**Comment by timvdstap** [comment]
Hi guys, would you happen to have an update on this issue? Do you reckon it's possible to merge those two sections for the IYS CKAN?

**Comment by Br-Johnson** [comment]
I think this issue is blocked by https://github.com/cioos-siooc/ckan/issues/119 
and what happens with the CIOOS catalogue will likely determine what happens with the IYS catalogue

**Comment by fostermh** [comment]
The difference between the two fields is: 'Point of Contact' is a list of the primary people who should be contacted regarding the data or metadata. while 'Responsible Party' is the list of people who should be given credit for contributing to the dataset in some way, thus appear in the 'citation'. 

Do you want the tech who working on this project for 3 months 6 years ago to be the primary contact even though they were very important at the time but have not looked at the data or thought about it since then? Or should the primary contact be the PI or the person currently responsible for managing the ongoing data collection? I don't know but keeping them separate allows for this flexibility. 

Is the issue here that the ckan interface is confusing? or that the metadata intake form is misleading and users are confused by the outcome? These are two different issues in my mind that appear to be treated as one.

**Comment by Br-Johnson** [comment]
If we kept the CKAN divisions I don't think we want the "tech who working on this project for 3 months 6 years ago to be the primary contact" ie. the custodian. I think we want the 'Data Owner' or PI listed in the Point of Contact section as per the suggestion/feedback here: https://github.com/cioos-siooc/metadata-entry-form/issues/126

Ultimately @timvdstap and I think the division in CKAN is superfluous and confusing though. Most people can just look at the citation and find the first author's email to contact them.

**Comment by fostermh** [comment]
that's an interesting point, hide both contacts and only show the citation. I had not considered that.

**Comment by Br-Johnson** [comment]
Sorry I meant people can find the authors email from a lumped list of 'Contacts' or 'Affiliated Parties' section in CKAN that would combine 'Point of Contact' and 'Responsible Party'.

**Comment by Br-Johnson** [comment]
This is done
